### ISSUE TITLE
No stable version found error when install with coursier

### ISSUE THREAD

**Issue by ckipp01** [sourcegraph/scip-java#450]
Hello! Just a heads up, with the way `cs install` works, there needs to be a stable version that exists or else you'll get an exception since the descriptor [here](https://github.com/coursier/apps/blob/master/apps-contrib/resources/scip-java.json#L6) is using `latest.stable` and there is only an RC version of `scip-java` available. Currently when someone tries to install it via `cs install --contrib scip-java` it will fail with:

```
❯ cs install --contrib scip-java
https://repo1.maven.org/maven2/io/get-coursier/apps/maven-metadata.xml
  No new update since 2022-05-16 11:11:57
Exception in thread "main" coursier.error.ResolutionError$CantDownloadModule: Error downloading com.sourcegraph:scip-java_2.13:latest.stable
  No latest stable version found in https://repo1.maven.org/maven2/com/sourcegraph/scip-java_2.13/maven-metadata.xml
        at coursier.Resolve$.$anonfun$validate$1(Resolve.scala:347)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at scala.collection.TraversableLike.map(TraversableLike.scala:286)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at coursier.Resolve$.validate(Resolve.scala:345)
        at coursier.Resolve.validate0$1(Resolve.scala:117)
        at coursier.Resolve.$anonfun$ioWithConflicts0$4(Resolve.scala:167)
        at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
        at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
        at coursier.util.Task$.wrap(Task.scala:82)
        at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:833)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:597)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:194)
```
I know `lsif-java` is still available in contrib, but just brining this to your attention in case you weren't aware.

**Comment by ckipp01** [comment]
Closing since there is a stable release out now.
