### ISSUE TITLE
NullPointerException indexing jdk v11 in auto-indexing

### ISSUE THREAD

**Issue by Strum355** [sourcegraph/scip-java#520]
Link to autoindexing job
https://sourcegraph.com/jdk/-/code-graph/indexes/TFNJRkluZGV4OjM5NDM0MDk=

```
Status: Downloaded newer image for sourcegraph/scip-java@sha256:eb3996bdc8ab3a56600e7d647bc1ef72f3db8cfffc2026550095a0af7bb762bd
+ scip-java index --build-tool=scip
Using JVM version '11'
Downloading https://raw.githubusercontent.com/coursier/jvm-index/master/index.json
Downloaded https://raw.githubusercontent.com/coursier/jvm-index/master/index.json
[94minfo[39m: Compiling 18,334 Java sources
Downloaded 1 missing file(s) / 24
Downloaded 2 missing file(s) / 24
Downloaded 3 missing file(s) / 24
Downloaded 4 missing file(s) / 24
Downloaded 5 missing file(s) / 24
Downloaded 6 missing file(s) / 24
Downloaded 7 missing file(s) / 24
Downloaded 8 missing file(s) / 24
Downloaded 9 missing file(s) / 24
Downloaded 10 missing file(s) / 24
Downloaded 11 missing file(s) / 24
Downloaded 12 missing file(s) / 24
Downloaded 13 missing file(s) / 24
Downloaded 14 missing file(s) / 24
Downloaded 15 missing file(s) / 24
Downloaded 16 missing file(s) / 24
Downloaded 17 missing file(s) / 24
Downloaded 18 missing file(s) / 24
Downloaded 19 missing file(s) / 24
Downloaded 20 missing file(s) / 24
Downloaded 21 missing file(s) / 24
Downloaded 22 missing file(s) / 24
Downloaded 23 missing file(s) / 24
Downloaded 24 missing file(s) / 24
[94minfo[39m: $ /root/.cache/coursier/arc/https/github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.16.1%252B1/OpenJDK11U-jdk_x64_linux_hotspot_11.0.16.1_1.tar.gz/jdk-11.0.16.1+1/bin/javac @/data/target/javacopts.txt
[94minfo[39m: An exception has occurred in the compiler (11.0.16.1). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
[94minfo[39m: java.lang.NullPointerException
[94minfo[39m: 	at jdk.compiler/com.sun.tools.javac.comp.Modules$UsesProvidesVisitor.visitExports(Modules.java:1011)
[94minfo[39m: 	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCExports.accept(JCTree.java:2743)
[94minfo[39m: 	at jdk.compiler/com.sun.tools.javac.comp.Modules$UsesProvidesVisitor.lambda$visitModuleDef$0(Modules.java:988)
[94minfo[39m: 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[94minfo[39m: 	at jdk.compiler/com.sun.tools.javac.comp.Modules$UsesProvidesVisitor.visitModuleDef(Modules.java:988)
[94minfo[39m: 	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCModuleDecl.accept(JCTree.java:2693)
[94minfo[39m: 	at jdk.compiler/com.sun.tools.javac.comp.Modules.lambda$getUsesProvidesCompleter$4(Modules.java:963)
[94minfo[39m: 	at jdk.compiler/com.sun.tools.javac.code.Symbol$ModuleSymbol.completeUsesProvides(Symbol.java:1009)
[94minfo[39m: 	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitModuleDef(Attr.java:4596)
[94minfo[39m: 	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCModuleDecl.accept(JCTree.java:2693)
[94minfo[39m: 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
[94minfo[39m: 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:724)
[94minfo[39m: 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribModule(Attr.java:4493)
[94minfo[39m: 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribModule(Attr.java:4484)
[94minfo[39m: 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attrib(Attr.java:4441)
[94minfo[39m: 	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1337)
[94minfo[39m: 	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:973)
[94minfo[39m: 	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:311)
[94minfo[39m: 	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
[94minfo[39m: 	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
[94minfo[39m: 	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)
[91merror[39m: CommandResult 4
time="2022-11-10T14:55:20Z" level=error msg="Process exited with status 1\n"
```

**Comment by olafurpg** [comment]
Can we work around this issue by using an older version of JDK v11? This was working before.

**Comment by Strum355** [comment]
I will try out multiple versions tomorrow/next week to see if I can narrow it down to that addressing it 🙂
