### ISSUE TITLE
Cannot run program "mill" when using mill wrapper

### ISSUE THREAD

**Issue by ghostbuster91** [sourcegraph/scip-java#533]
Hi,

I recently switched to use more automatic way of uploading metadata to sourcegraph that relies on `scip-java index` instead of manually calling `coursier`. In [my project](https://github.com/ghostbuster91/sttp-openapi-generator) I have both `sbt` and `mill` build tools, however mill binary is not committed to the repository. Instead I use [millw](https://github.com/lefou/millw) wrapper that manages mill binary on its own (similarly to how gradlw works for gradle). 

Unfortunately, setting `--build-tool=mill` doesn't work in such a setup and it fails with the following error:
```
Run scip-java index --build-tool=mill
$ mill --no-server --import ivy:io.chris-kipp::mill-scip::0.3.0 io.kipp.mill.scip.Scip/generate --output index.scip
java.io.IOException: Cannot run program "mill" (in directory "/home/runner/work/sttp-openapi-generator/sttp-openapi-generator"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:10[7](https://github.com/ghostbuster91/sttp-openapi-generator/actions/runs/4269856281/jobs/7433298441#step:4:8)3)
	at os.proc.proc$lzycompute$1(ProcessOps.scala:12[8](https://github.com/ghostbuster91/sttp-openapi-generator/actions/runs/4269856281/jobs/7433298441#step:4:9))
	at os.proc.proc$1(ProcessOps.scala:122)
	at os.proc.spawn(ProcessOps.scala:135)
	at moped.cli.SpawnableProcess.spawn(Processes.scala:161)
	at moped.cli.SpawnableProcess.call(Processes.scala:8[9](https://github.com/ghostbuster91/sttp-openapi-generator/actions/runs/4269856281/jobs/7433298441#step:4:10))
	at com.sourcegraph.scip_java.commands.IndexCommand.process(IndexCommand.scala:81)
	at com.sourcegraph.scip_java.buildtools.MillBuildTool.unconditionallyGenerateScip(MillBuildTool.scala:49)
	at com.sourcegraph.scip_java.buildtools.MillBuildTool.generateScip(MillBuildTool.scala:19)
	at com.sourcegraph.scip_java.commands.IndexCommand.run(IndexCommand.scala:161)
	at moped.cli.Command.$anonfun$runAsFuture$1(BaseCommand.scala:14)
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.scala:17)
	at scala.util.Try$.apply(Try.scala:2[10](https://github.com/ghostbuster91/sttp-openapi-generator/actions/runs/4269856281/jobs/7433298441#step:4:11))
	at moped.cli.Command.runAsFuture(BaseCommand.scala:14)
	at moped.cli.Application$.$anonfun$run$7(Application.scala:328)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:434)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:[11](https://github.com/ghostbuster91/sttp-openapi-generator/actions/runs/4269856281/jobs/7433298441#step:4:12)82)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:3[14](https://github.com/ghostbuster91/sttp-openapi-generator/actions/runs/4269856281/jobs/7433298441#step:4:15))
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:[24](https://github.com/ghostbuster91/sttp-openapi-generator/actions/runs/4269856281/jobs/7433298441#step:4:25)4)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
```

Expected behavior:

`scip` should perform a check to see if there is a `millw` regular file as it is done in https://github.com/sourcegraph/scip-java/blob/main/scip-java/src/main/scala/com/sourcegraph/scip_java/buildtools/GradleBuildTool.scala#L42 for gradlew and use if there is, it should use `millw` instead of `mill`. 

Additional info:
PR that contains commits where the problem occured: https://github.com/ghostbuster91/sttp-openapi-generator/pull/246

**Comment by jdorfman** [comment]
@ghostbuster91 looks like you fixed it. I'm going to close this for now, feel free to reopen if needed

**Comment by ghostbuster91** [comment]
Well, I fixed the integration with sourcegraph in my repository by switching to a different build tool. That doesn't mean that this issue has been resolved. I made a PR in #534 that fixes it. I would wait for it to be merged.

**Comment by jdorfman** [comment]
@ghostbuster91 my bad! Done.
