### ISSUE TITLE
Auto-indexing of Gradle 8 projects doesn't work

### ISSUE THREAD

**Issue by keynmol** [sourcegraph/scip-java#544]
The docker tag is irrelevant, I built two different images with different preloaded gradle version and both failed.

What matters is that the gradle wrapper version is 8+.
Repo doesn't matter - you can get the same results on a repo made from `gradle init` with all default settings.

This can also be seen in tests that do not set gradle version explicitly - they run `gradle wrapper` and get whatever the CI image is using.

Once this is fixed, we should really run a job matrix for gradle version.

```
> docker run -w /source -v (pwd):/source -it sourcegraph/scip-java:latest-gradle8 scip-java index --build-tool=gradle
Using JVM version '17'
$ /source/gradlew --init-script /tmp/scip-java405071211554974201/java-toolchains.gradle scipDetectJavaToolchains
Downloading https://services.gradle.org/distributions/gradle-8.0.2-bin.zip
...........10%............20%............30%............40%............50%............60%...........70%............80%............90%............100%

Welcome to Gradle 8.0.2!

Here are the highlights of this release:
 - Improvements to the Kotlin DSL
 - Fine-grained parallelism from the first build with configuration cache
 - Configurable Gradle user home cache cleanup

For more details see https://docs.gradle.org/8.0.2/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)
> Task :scipDetectJavaToolchains

BUILD SUCCESSFUL in 18s
1 actionable task: 1 executed
$ /source/gradlew --no-daemon --init-script /tmp/scip-java405071211554974201/init-script.gradle -Porg.gradle.java.installations.auto-detect=false -Porg.gradle.java.installations.auto-download=false -Porg.gradle.java.installations.paths=/tmp/scip-java405071211554974201/1.17 clean scipJavaDependencies
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/8.0.2/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build
> Task :clean
> Task :scipJavaDependencies

BUILD SUCCESSFUL in 3s
2 actionable tasks: 2 executed
java.lang.RuntimeException: No SemanticDB files found. This typically means that `scip-java` is unable to automatically index this codebase. If you are using Gradle or Maven, please report an issue to https://github.com/sourcegraph/scip-java and include steps to reproduce. If you are using a different build tool, make sure that you have followed all of the steps from https://sourcegraph.github.io/scip-java/docs/manual-configuration.html
        at com.sourcegraph.scip_semanticdb.ScipSemanticdbReporter.error(ScipSemanticdbReporter.java:13)
        at com.sourcegraph.scip_semanticdb.ScipSemanticdb.run(ScipSemanticdb.java:46)
        at com.sourcegraph.scip_semanticdb.ScipSemanticdb.run(ScipSemanticdb.java:37)
        at com.sourcegraph.scip_java.commands.IndexSemanticdbCommand.run(IndexSemanticdbCommand.scala:90)
        at com.sourcegraph.scip_java.buildtools.BuildTool$.generateScipFromTargetroot(BuildTool.scala:51)
        at com.sourcegraph.scip_java.buildtools.GradleBuildTool.generateScip(GradleBuildTool.scala:25)
        at com.sourcegraph.scip_java.commands.IndexCommand.run(IndexCommand.scala:161)
        at moped.cli.Command.$anonfun$runAsFuture$1(BaseCommand.scala:14)
        at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.scala:17)
        at scala.util.Try$.apply(Try.scala:210)
        at moped.cli.Command.runAsFuture(BaseCommand.scala:14)
        at moped.cli.Application$.$anonfun$run$7(Application.scala:328)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:434)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
info: /source/index.scip
```

**Comment by keynmol** [comment]
For all intents and purposes, this works (as of `0.8.20`) - we even have [tests](https://github.com/sourcegraph/scip-java/blob/main/tests/buildTools/src/test/scala/tests/GradleBuildToolSuite.scala#L11) for that now

Please reopen if it doesn't
