### ISSUE TITLE
`SignatureFormatterException` indexing this repo

### ISSUE THREAD

**Issue by feifanzhou** [sourcegraph/scip-java#753]
After cloning this repo and running `coursier launch com.sourcegraph:scip-java_2.13:0.10.3 -- index --build-tool=sbt`, it runs into an error:

```
Generating SCIP... [          ] 0%   0 files processedcom.sourcegraph.scip_semanticdb.SignatureFormatterException: failed to format symbol 'minimized/Foo#test().'
symbol: "minimized/Foo#test()."
kind: METHOD
properties: 4
display_name: "test"
annotations {
  tpe {
    type_ref {
      symbol: "minimized/Bar#"
    }
  }
  parameters {
    assign_tree {
      lhs {
        id_tree {
          symbol: "minimized/Bar#value()."
        }
      }
      rhs {
        12: {
          2: {
            4: {
              1: {
                9: {
                  1: 0x3ff0000000000000
                }
              }
            }
          }
        }
      }
    }
  }
}
signature {
  method_signature {
    type_parameters {
    }
    parameter_lists {
    }
    return_type {
      type_ref {
        symbol: "scala/Double#"
      }
    }
  }
}
access {
  public_access {
  }
}

Caused by: java.lang.IllegalArgumentException: tree was of unexpected type 12: {
  2: {
    4: {
      1: {
        9: {
          1: 0x3ff0000000000000
        }
      }
    }
  }
}

	at com.sourcegraph.scip_semanticdb.SignatureFormatter.formatTree(SignatureFormatter.java:473)
	at com.sourcegraph.scip_semanticdb.SignatureFormatter.formatAnnotation(SignatureFormatter.java:419)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.sourcegraph.scip_semanticdb.SignatureFormatter.formatAnnotations(SignatureFormatter.java:399)
	at com.sourcegraph.scip_semanticdb.SignatureFormatter.formatAnnotations(SignatureFormatter.java:393)
	at com.sourcegraph.scip_semanticdb.SignatureFormatter.formatMethodSignature(SignatureFormatter.java:217)
	at com.sourcegraph.scip_semanticdb.SignatureFormatter.formatSymbolUnsafe(SignatureFormatter.java:69)
	at com.sourcegraph.scip_semanticdb.SignatureFormatter.formatSymbol(SignatureFormatter.java:58)
	at com.sourcegraph.scip_semanticdb.ScipSemanticdb.processTypedDocument(ScipSemanticdb.java:194)
	at com.sourcegraph.scip_semanticdb.ScipSemanticdb.lambda$runTyped$0(ScipSemanticdb.java:69)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[error] (ThisBuild / sourcegraphCompile) com.sourcegraph.sbtsourcegraph.SourcegraphPlugin$TaskException: '/Users/feifan/Developer/scip-java/target/sbt-sourcegraph/coursier' failed with exit code '1'. To reproduce this error, run the following command:
[error] /Users/feifan/Developer/scip-java/target/sbt-sourcegraph/coursier launch com.sourcegraph:scip-java_2.13:0.9.5 -M com.sourcegraph.scip_java.ScipJava -- index-semanticdb --output=/Users/feifan/Developer/scip-java/target/sbt-sourcegraph/index.scip /Users/feifan/Developer/scip-java/tests/unit/target/scala-2.13/test-meta/META-INF/semanticdb /Users/feifan/Developer/scip-java/scip-java/target/scala-2.13/meta/META-INF/semanticdb /Users/feifan/Developer/scip-java/tests/unit/target/scala-2.13/meta/META-INF/semanticdb /Users/feifan/Developer/scip-java/scip-java-proto/target/semanticdb-classes/META-INF/semanticdb /Users/feifan/Developer/scip-java/semanticdb-java/target/semanticdb-classes/META-INF/semanticdb /Users/feifan/Developer/scip-java/scip-semanticdb/target/semanticdb-classes/META-INF/semanticdb /Users/feifan/Developer/scip-java/semanticdb-gradle-plugin/target/scala-2.13/meta/META-INF/semanticdb /Users/feifan/Developer/scip-java/semanticdb-agent/target/semanticdb-classes/META-INF/semanticdb /Users/feifan/Developer/scip-java/tests/snapshots/target/scala-2.13/meta/META-INF/semanticdb /Users/feifan/Developer/scip-java/tests/snapshots/target/scala-2.13/test-meta/META-INF/semanticdb /Users/feifan/Developer/scip-java/maven-plugin/target/semanticdb-classes/META-INF/semanticdb /Users/feifan/Developer/scip-java/tests/minimized/.j11/target/meta/META-INF/semanticdb /Users/feifan/Developer/scip-java/tests/minimized-scala/target/scala-2.13/meta/META-INF/semanticdb
[error] Total time: 72 s (01:12), completed Oct 7, 2024, 6:23:38 PM
Generating SCIP... [          ] 0%   0 files processed
```

**Comment by jupblb** [comment]
The code that caused the crash no longer exists.
